# Generated by Django 2.1.7 on 2019-04-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_theater_max_occupancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showing',
            name='theater',
        ),
        migrations.AddField(
            model_name='show',
            name='theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Theater'),
        ),
    ]
