# Generated by Django 2.1.7 on 2019-04-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20190422_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='max_occupancy',
            field=models.IntegerField(default=60, help_text='Enter the total number of seats.'),
        ),
    ]
