# Generated by Django 2.1.7 on 2019-05-20 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_theater_max_occupancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='uuid',
        ),
        migrations.AddField(
            model_name='bookedticket',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='AreaDesc',
            field=models.CharField(default='Tandard', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='PhyRowId',
            field=models.CharField(default='A', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='SeatNumber',
            field=models.IntegerField(default=1),
        ),
    ]
