# Generated by Django 2.1.7 on 2019-05-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20190520_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='AreaDesc',
            field=models.CharField(default='standard', max_length=20),
        ),
    ]
