# Generated by Django 2.1.7 on 2019-06-07 00:51

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20190521_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='receipt',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=27, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='paid_amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='USD', max_digits=10, null=True),
        ),
    ]
