# Generated by Django 2.1.7 on 2019-06-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20190606_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seatId',
            field=models.CharField(default='<django.db.models.fields.CharField><django.db.models.fields.IntegerField>', editable=False, max_length=20),
        ),
    ]
