# Generated by Django 2.1.7 on 2019-06-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_ticket_seatid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seatId',
            field=models.CharField(default='A1', max_length=20),
        ),
    ]
