# Generated by Django 2.1.7 on 2019-10-14 21:09

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20190606_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=markdownx.models.MarkdownxField(default='This is an empty description.'),
        ),
    ]
