# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-04 00:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('payment_type', models.CharField(choices=[('PAYPAL', 'PayPal')], default='PayPal', max_length=11)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('director', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(choices=[('ENGLISH', 'English')], max_length=10)),
                ('run_length', models.IntegerField(blank=True, help_text="Enter run length in minute's", null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Show')),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_occupancy', models.IntegerField(blank=True, null=True)),
                ('location_link', models.CharField(blank=True, help_text='Copy the goo.gl share link from google maps', max_length=32, null=True)),
                ('frame_link', models.CharField(blank=True, help_text='Click "Copy Link" then Embed a map the src lin in this field', max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Showing')),
            ],
        ),
        migrations.AddField(
            model_name='showing',
            name='theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Theater'),
        ),
        migrations.AddField(
            model_name='bookedticket',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booking'),
        ),
        migrations.AddField(
            model_name='bookedticket',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Ticket'),
        ),
    ]
