# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-04 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='timestamp',
            new_name='datetime',
        ),
        migrations.AddField(
            model_name='bookedticket',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
