# Generated by Django 2.1.7 on 2019-03-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190309_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='invoice',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
